export const termsOfService = `
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:8.0pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:40px;color:#1F3864;'>Croptor - Terms of Use</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:14px;color:#1F3864;'>Last update: 23 JAN 2024</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:14px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>Croptor - Image Cropping Tool operates this Site ( www.Croptor.com &nbsp;) provide an Image Cropping Service. By accessing and using this Site, you agree to each of the terms and conditions set forth herein (&ldquo;Terms of Use&rdquo;). These Terms of Use are referred to hereunder as &ldquo;Agreement.&rdquo; Croptor - Image Cropping Tool reserves the right to modify this Agreement at any time without giving you prior notice. Your use of the Site following any such modification constitutes your agreement to follow and be bound by the Agreement as modified.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:8.0pt;font-size:11.0pt;'><span style='color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>1. Use of the Site</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;background:white;'><span style='font-size:18px;color:#1F3864;'>You may use the Site and its Functionality for your personal purposes. You may copy or download the Content of the Site, provided that you maintain the Copyright, Trademark or related notices in the Content. No right, title or interest in any Content is transferred to you, whether as a result of downloading such Content or otherwise. Except as authorized by this Agreement, you may not use, alter, copy, distribute, transmit, or derive another work from any Content obtained from the Site.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;background:white;'><span style='font-size:18px;color:#1F3864;'>If you register to become an Croptor - Image Cropping Tool member, you are responsible for maintaining the confidentiality of your member identification and password information, and for restricting access to your computer. You agree to accept responsibility for all activities that occur under your member identification and password.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;background:white;'><span style='font-size:18px;color:#1F3864;'>You agree to use the Site only for lawful purposes. You agree not to add to, subtract from, or otherwise modify the Content, or to attempt to access any Content that is not intended for you. You agree not to use the Site in any manner that might interfere with the rights of third parties. You agree not to take any action that might compromise the security of the Site, render the Site inaccessible to others or otherwise cause damage to the Site or the Content. You will not input or upload to the Site any information which contains viruses, Trojan horses, worms, time bombs or other computer programming routines that are intended to damage, interfere with, intercept or expropriate the Site. harvest or otherwise collect or store personal data about others, including email addresses;</span></p>
<ol style="list-style-type: decimal;margin-left:26px;">
    <li><span style='font-size:13.5pt;color:#1F3864;'>create a false identity for the purpose of misleading others;</span></li>
    <li><span style='font-size:13.5pt;color:#1F3864;'>create an inappropriate (e.g. vulgar, offensive etc) screen name;</span></li>
    <li><span style='font-size:13.5pt;color:#1F3864;'>violate any applicable laws or regulations.</span></li>
</ol>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:18px;color:#1F3864;'>You agree that any material, information, or data you transmit to us or post to the Site (each a &ldquo;Submission or collectively &ldquo;Submissions&rdquo;) will be considered non confidential and non proprietary. For all Submissions, (1) you guarantee to us that you have the legal right to post the Submission and that it will not violate any law or the rights of any person or entity, and (2) Croptor - Image Cropping Tool does not claim ownership of Content you submit or make available on Croptor - Image Cropping Tool. However, with respect to Content you submit or make available on Croptor - Image Cropping Tool, you grant Croptor - Image Cropping Tool the royalty-free, irrevocable, perpetual, worldwide right to use, distribute, display and create derivative works from the Submission, in any and all media, in any manner, in whole or in part, without any restriction or responsibilities to you. Croptor - Image Cropping Tool reserves the right to remove any Content from the Site at any time and for any reason.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:18px;color:#1F3864;'>Croptor - Image Cropping Tool welcomes feedback regarding ideas that will help satisfy user&rsquo;s needs and feedback can be provided through the &ldquo;Contact us&rdquo; area on the Site. By sending us your comments and ideas, you acknowledge that (1) they will not be considered confidential or proprietary, (2) Croptor - Image Cropping Tool is under no obligation to keep such information confidential, and (3) Croptor - Image Cropping Tool will have an unrestricted, irrevocable, world-wide, royalty free right to use, communicate, reproduce, publish, display, distribute and exploit such comments and ideas in any manner it chooses.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:18px;color:#1F3864;'>Croptor - Image Cropping Tool will use reasonable efforts to ensure that the Site and Services are available twenty-four hours a day, seven days a week. However, there will be occasions when the Site and/or Services will be interrupted for maintenance, upgrades and emergency repairs or due to failure of telecommunications links and equipment. Every reasonable step will be taken by Croptor - Image Cropping Tool to minimize such disruption where it is within Croptor - Image Cropping Tool&rsquo;s reasonable control. YOU AGREE THAT NEITHER CROPTOR - IMAGE CROPPING TOOL NOR THE SITE WILL BE LIABLE IN ANY EVENT TO YOU OR ANY OTHER PARTY FOR ANY SUSPENSION, MODIFICATION, DISCONTINUANCE OR LACK OF AVAILABILITY OF THE SITE, THE SERVICES, YOUR USER CONTENT (AS DEFINED HEREIN) OR OTHER CONTENT.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:18px;color:#1F3864;'>You shall be responsible for obtaining and maintaining any equipment or ancillary services needed to connect to, access the Site or otherwise use the Services, including, without limitation, modems, hardware, software, and long distance or local telephone service. You shall be responsible for ensuring that such equipment or ancillary services are compatible with the Services.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>2. Links to third-party websites</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:18px;color:#1F3864;'>Links on the Croptor - Image Cropping Tool Site to third party websites or information are provided as a convenience to you. If you use these links, you will leave the Croptor - Image Cropping Tool Site. Such links do not constitute or imply an endorsement, sponsorship, or recommendation by Croptor - Image Cropping Tool of the third party or the information contained therein. Croptor - Image Cropping Tool is not responsible or liable for any such website or the content thereon. Croptor - Image Cropping Tool is not responsible for the availability of any such websites. If you use the links to the websites of Croptor - Image Cropping Tool affiliates or service providers, you will leave the Site, and will be subject to the terms of use and privacy policy applicable to those web sites.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>3. Warranty Disclaimer</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:18px;color:#1F3864;'>Croptor - Image Cropping Tool makes no warranties, representations or endorsements whatsoever with respect to the Site or the Content. Croptor - Image Cropping Tool expressly disclaims all warranties of any kind, express, implied, statutory or otherwise, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, with regard to the Site and the Content offered by the Site. Croptor - Image Cropping Tool does not warrant that the functions performed by the Site will be uninterrupted, timely, secure or error-free, or that defects in the Site will be corrected. Croptor.com does not warrant the accuracy or completeness of the Content, or that any errors in the Content will be corrected. Croptor.com does not warrant that files available for downloading through the Site will be free of infection by software viruses or other computer programs. The Croptor.com Site and its Content are provided on an &ldquo;As is&rdquo; and &ldquo;As available&rdquo; basis.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>4. Limitation of liability</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:18px;color:#1F3864;'>In no event will Croptor.com be liable for any damages whatsoever including, but not limited to any direct, incidental, consequential, special, exemplary or other indirect damages arising out of (1) the useof or inability to use the Site or the Content, (2) any transaction conducted through or facilitated by the Site, (3) any claim attributable to errors, omissions, or other inaccuracies in the Site and/or the Content, (4) unauthorised access to or alteration of your transmissions or data, or (5) any other matter relating to the Site or the Content, even if Croptor.com has been advised of the possibility of such damages.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>5. Indemnification</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:18px;color:#1F3864;'>You understand and agree that you are personally responsible for your behavior on the Site. You agree to indemnify, defend and hold harmless Croptor - Image Cropping Tool, its parent company, subsidiaries, affiliated companies, joint venturers, business partners, licensors, employees, agents, and any third-party information providers to the Site from and against all claims, losses, expenses, damages and costs (including, but not limited to, direct, incidental, consequential, exemplary and indirect damages), and reasonable attorneys&rsquo; fees, resulting from or arising out of your use, misuse, or inability to use the Site or the Content, or any violation by you of this Agreement</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>6. Payment methods</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;background:white;'><span style='font-size:18px;color:#1F3864;'>We currently accept all major payment methods via Wayforpay which accepts Visa, Mastercard, Privat24, Gpay, Apple pay and more</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;line-height:normal;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>7</span></strong><strong><span style='font-size:18px;color:#1F3864;'>. General provisions</span></strong></p>
<ol style="list-style-type: decimal;margin-left:26px;">
    <li><span style='font-size:13.5pt;color:#1F3864;'>The Content of the Site may contain typographical or other errors or inaccuracies and may not be complete or current. Croptor.com reserves the right to correct errors, inaccuracies or omissions and to change or update the Content at any time without prior notice. Croptor.com does not guarantee that any errors, inaccuracies or omissions will be corrected.</span></li>
    <li><span style='font-size:13.5pt;color:#1F3864;'>Juridical enforcement. If any part of this Agreement is determined by a court of competent jurisdiction to be invalid or unenforceable, it will not impact any other provision of this Agreement, all of which will remain in full force and effect. Any and all disputes relating to this Agreement, your use of the Site or the Content are governed by, and will be interpreted in accordance with, the laws of the Ukraine, without regard to any conflict of laws provisions.</span></li>
    <li><span style='font-size:13.5pt;color:#1F3864;'>These Terms of Use constitute the entire agreement of the parties with respect to the subject matter hereof. No waiver by Croptor.com of any breach or default hereunder shall be deemed to be a waiver of any preceding or subsequent breach or default.</span></li>
</ol>
`
export const refundPolicy= `
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:40px;color:#1F3864;'>Croptor Refund Policy</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:14px;color:#1F3864;'>Last update: 23 JAN 2024</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:14px;color:#1F3864;'>&nbsp;</span></p>
<ol style="list-style-type: decimal;margin-left:8px;">
    <li><span style='font-size:13.5pt;color:#1F3864;'>As our product is saas service, we are able to refund the funds of subscription cost if you claim a refund during 3 business days.&nbsp;</span></li>
    <li><span style='font-size:13.5pt;color:#1F3864;'>We are happy to issue a refund if you subscribed to PRO plan for more months that you wanted to by mistake.</span></li>
    <li><span style='font-size:13.5pt;color:#1F3864;'>Please make sure when you subscribe to the service that it is what you want, as mistakes cannot be seen as a reason for refunds. Please try service for free and meet it&rsquo;s functions before the purchase of paid plan.</span></li>
    <li><span style='font-size:13.5pt;color:#1F3864;'>The customer is responsible to have the knowledge required to use the product.</span></li>
    <li><span style='font-size:13.5pt;color:#1F3864;'>If you are in any doubt as to the suitability of the service or have any questions, please contact us directly at support@croptor.com before you purchase to ensure that it is suitable for your purposes.</span></li>
</ol>
`
export const privacyPolicy = `
<h2 style='margin-right:0cm;margin-left:0cm;font-size:24px;font-weight:bold;margin-top:0cm;background:white;'><span style='font-size:40px;color:#1F3864;font-weight:normal;'>Croptor Privacy Policy</span></h2>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:8.0pt;font-size:11.0pt;background:white;'><span style='font-size:14px;color:#1F3864;'>Last update: 23 JAN 2024</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>The protection of your privacy and personal information is of the utmost importance to Croptor.com . This Privacy Policy gives transparency to the information we collect, how we use it and the steps we take to protect it. The policy governs all the products and services we provide throughout the website. When you use the site, you consent to the way we collect, manage and protect your data as described in this document.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>1 Information you share with us</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>1.1 Your user account</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>When you sign up for a personal account at Croptor.com &nbsp;we save your name, email and password. Passwords are saved encrypted. If you forget your email you can reset your password via a link that can be sent to the email address with which you created the account. In your personal account you are free to add your occupation, location, your interests, brands you want to follow and create a first collection during the sign-up phase. There is an option to skip all this. Croptor.com &nbsp;can use this anonymized information to give clients insight into the demographics of its users and can use this anonymized information to offer you content linked to your interests, followed companies, profession and collections.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>You are also free to add your gender and birthdate. Croptor.com &nbsp;will never share this with other parties. As an option, you can add a profile picture and cover photo to your personal account and add a short description. When you login via facebook or linkedin, Croptor.com &nbsp;automatically adds your profile image from the respective social media profile. The profile picture is visible if you link your personal account to a brand account as a team member, then your profile images and name will be shown in the team member section of the brand you connected to. The personal profile page is visible to the public, but you can turn this off in your settings by making your profile private.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>1.2 Collection</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>When you make a collection your profile picture will be shown on the collection page and next to the collection card on the homepage if it is featured. When you save your favourite products or projects in a collection, you can choose to make this private or public. Visitors will only be able to see a public collection.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>1.3 Newsletters</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>Croptor.com &nbsp;offers newsletters. This way you can receive updates on the most interesting posts of the week or get notifications about new products or projects from your favorite companies, about upcoming events, new functions and offers. To make sure you only get newsletters that you wish to receive, you must explicitly opt-in. Our newsletters are sent via Sendgrid, Inc. (US), which receives the required information from us.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>1.4 Request and contact forms</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>On a product page you can send a variety of requests about the product itself or the brand of the product. You can ask a product brand for more information, request prices, documentation, request and download catalogues, 3D files, or request available suppliers. On a brand page you can contact a brand via the contact button. In order to respond to your request, the brand requires some of your information. The personal information you provide in the form will be shared with the contacted party. When you are logged into your personal account, automatically your name and email will be placed in the form. You can choose whether to make a request or not.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>1.5 Follow</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>Every company on Croptor.com &nbsp;has a follow button on their brand page. You can click on the follow button to get updates from a brand you are interested in. When a brand you are following adds a new project, product or article, you will receive an email notification from Croptor.com &nbsp;about this new publication. In your sign-up you need to explicitly opt-in for these emails. In your account settings you can choose to turn this off or on. On the brand page of the company you follow, your name and profile picture are visible on their followers page.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>1.6 Personal profile visibility</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>An open profile is visible for the public and indexed by search engines. This profile contains your name and added profile information (see 1.1), the collections you created and it shows the brands you are following. On the followers page of the brands you follow, your name and profile picture will also be visible. Brands you are connected to or created will also show your profile photo and name.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>In the case you do not want your profile to be visible, you can use the setting &apos;Hide my profile&apos; in your personal profile settings. With this &lsquo;Hide my profile&rsquo; setting your personal profile page will change into an anonymous page for the public.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>1.7 Activity</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>With certain actions on Croptor.com , a company will receive a record of the action if it relates to their profile. When you save a product or project to a collection, click on a website link, download an image, or use any of the contact buttons, the company related to the item on Croptor.com &nbsp;will see your public profile name mentioned in an activity list next to the action you performed. Only your username and profile image are visible, nothing more will be shared (such as your email or other contact information).</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>If you don&apos;t want your name to be visible, also for this you can &lsquo;Hide your profile&rsquo; in the personal profile settings and instead of your name in the activity list, it will say &lsquo;anonymous&rsquo;.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>2 Information we collect</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>2.1 Devices</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>To optimize the website on relevant devices, screen sizes, browsers and operating systems, we collect information about the device through which you visit the site, and which screen size, browser and operating system you use. The information about how visitors use our site is anonymized and encrypted by Google Analytics.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>2.2 Server logs</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>Information stored includes which route you entered the site, how long you stayed, which pages you visited, etc. This information is processed into general statistics Croptor.com &nbsp;and its clients can look into.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>2.3 Local storage</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>It is possible we store data, also of a personal nature, on your local device via mechanisms in your web browser storage and your device&rsquo;s data caches.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>3 Cookies</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>3.1 What are cookies</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>A cookie is a small text file that is stored in your computer via your web browser. Your device gets a unique number in order to recognize it. There are two types of cookies. Session cookies and temporary or permanent cookies. The session cookies are deleted as soon as you close the browser. The temporary and permanent cookies stay on your device. Croptor.com &nbsp;uses this information to improve its website experience.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>3.2 Which cookies does Croptor.com &nbsp;use</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>Most of the cookies we use are session cookies, which are immediately delted after you close the browser. Session cookies are for example</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>4 Data</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>4.1 Safe storage of your data</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>The personal information you provide Croptor.com &nbsp;is safely stored. Your information is stored for an indeterminate amount of time so that you don&apos;t have to provide this information again. Both the website and the services Croptor.com &nbsp;uses are protected and designed in a way such that only employees who absolutely need access in order to perform their tasks can get access. Croptor.com &nbsp;has an assigned privacy officer who oversees that your privacy is protected.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>4.2 Data Retention</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>We will keep and use your data as long as your account is in use, is open, or is active; as long as is necessary to comply with any tax, legal, and/or other regulations; and to protect and defend against potential legal claims. If you would like to request your personally identifiable information or request that it be returned to you, please contact us at support@Croptor.com.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>4.3 For legal reasons</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>Croptor.com &nbsp;shares personal information with companies, organisations or persons, when employees of Croptor.com &nbsp;seem due necessary in order to comply with the law, regulations or enforceable government requests, in cases where we need to investigate possible fraud, security risks, violations of our terms, and in order to protect the rights and safety or Croptor.com &nbsp;and its users.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>4.4 Trend insights</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>Information that cannot be traced back to an individual we can use with our clients or users. This way we can show developments in how our services are used.</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><strong><span style='font-size:18px;color:#1F3864;'>4.5 Changes</span></strong></p>
<p style='margin-right:0cm;margin-left:0cm;font-size:16px;margin-top:0cm;margin-bottom:.0001pt;font-size:11.0pt;margin:0cm;line-height:22.5pt;background:white;'><span style='font-size:18px;color:#1F3864;'>We retain the right to alter this document at a later time. The latest version of the policy applies. If we make profound changes to the policy, the user will be informed about these changes.</span></p>
`
export const contactUs = `
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:40px;color:#1F3864;'>Contact Us</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:40px;color:#1F3864;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:21px;color:#1F3864;'>Phone : +380933722467</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:21px;color:#1F3864;'>Email :&nbsp;</span><a href="mailto:support@croptor.com"><span style='font-size:21px;'>support@croptor.com</span></a></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;font-size:11.0pt;line-height:normal;background:white;'><span style='font-size:21px;color:#1F3864;'>Adress : Ukraine, Cherkassy region, Ternovka, Zarechnaya 29, 20733</span></p>
`